/**
 * Created by King Lee on 14-9-12.
 */
module.exports = {
    TYPE_TIME:{
        TYPE_TIME_TODAY :0,
        TYPE_TIME_THIS_MONTH :1,
        TYPE_TIME_THIS_YEAR:2,
        TYPE_TIME_HOUR:3
    },
    TYPE_FUTURE_TIME:{
        TYPE_FUTURE_TIME_TODAY :0,
        TYPE_FUTURE_TIME_MONTH :1,
        TYPE_FUTURE_TIME_YEAR:2
    },
    TYPE_COMPASS:{
        TYPE_COMPASS_ENERGY:0,
        TYPE_COMPASS_WEALTH:1,
        TYPE_COMPASS_LUCK:2,
        TYPE_COMPASS_PEACH:3
    },
    TYPE_SELECT_DATE:{
        TYPE_SELECT_DATE_DO_SOMETHING:0,
        TYPE_SELECT_DATE_MOVING:1,
        TYPE_SELECT_DATE_WEALTH:2,
        TYPE_SELECT_DATE_TRADE:3,
        TYPE_SELECT_DATE_OPENING:4,
        TYPE_SELECT_DATE_DATE:5,
        TYPE_SELECT_DATE_TALKING_SOMETHING:6,
        TYPE_SELECT_DATE_MEET_FRIEND:7,
        TYPE_SELECT_DATE_TRIP:8,
        TYPE_SELECT_DATE_INTERVIEW:9
    },
    TYPE_SELECT_DAYS:{
        TYPE_SELECT_DAYS_TEN:0,
        TYPE_SELECT_DAYS_THIRTY:1,
        TYPE_SELECT_DAYS_NINETY:2
    },
    TYPE_SCORE:{
        TYPE_SCORE_LUCK:0,
        TYPE_SCORE_WEALTH:1,
        TYPE_SCORE_EMOTION:2,
        TYPE_SCORE_ENERGY:3,
        TYPE_SCORE_WORK:4,
        TYPE_SCORE_LOST_WEALTH:5,
        TYPE_SCORE_PEACH:6
    }
};