/**
 * Created by King Lee on 14-9-12.
 */
module.exports = {
    TYPE_TIME:{
        TYPE_TIME_TODAY :0,
        TYPE_TIME_THIS_MONTH :1,
        TYPE_TIME_THIS_YEAR:2,
        TYPE_TIME_HOUR:3
    },
    FIXATION_TYPE_TIME:{
        TYPE_TIME_THIS_LISE :0,
        TYPE_TIME_IN_THE_PAST :1
    },
    TYPE_FUTURE_TIME:{
        TYPE_FUTURE_TIME_TODAY :0,
        TYPE_FUTURE_TIME_MONTH :1,
        TYPE_FUTURE_TIME_YEAR:2
    },
    TYPE_COMPASS:{
        TYPE_COMPASS_ENERGY:0,
        TYPE_COMPASS_WEALTH:1,
        TYPE_COMPASS_LUCK:2,
        TYPE_COMPASS_PEACH:3
    },
    TYPE_SELECT_DATE:{
        TYPE_SELECT_DATE_DO_SOMETHING:0,
        TYPE_SELECT_DATE_MOVING:1,
        TYPE_SELECT_DATE_WEALTH:2,
        TYPE_SELECT_DATE_TRADE:3,
        TYPE_SELECT_DATE_OPENING:4,
        TYPE_SELECT_DATE_DATE:5,
        TYPE_SELECT_DATE_TALKING_SOMETHING:6,
        TYPE_SELECT_DATE_MEET_FRIEND:7,
        TYPE_SELECT_DATE_TRIP:8,
        TYPE_SELECT_DATE_INTERVIEW:9
    },
    TYPE_SELECT_DAYS:{
        TYPE_SELECT_DAYS_TEN:0,
        TYPE_SELECT_DAYS_THIRTY:1,
        TYPE_SELECT_DAYS_NINETY:2
    },
    TYPE_SCORE:{
        TYPE_SCORE_LUCK:0,
        TYPE_SCORE_WEALTH:1,
        TYPE_SCORE_EMOTION:2,
        TYPE_SCORE_ENERGY:3,
        TYPE_SCORE_WORK:4,
        TYPE_SCORE_LOST_WEALTH:5,
        TYPE_SCORE_PEACH:6,
        TYPE_SCORE_BLESS:7
    },
    TYPE_FIXATION:{
        TYPE_FIXATION_BLESS:0,
        TYPE_FIXATION_ENERGY:1,
        TYPE_FIXATION_LUCK:2,
        TYPE_FIXATION_WEALTH:3,
        TYPE_FIXATION_PEACH:4,
        TYPE_FIXATION_LUCK_LAST_TEN_YEARS:5
    },
    TYPE_MATCH:{
        TYPE_MATCH_NATURE:0,
        TYPE_MATCH_MARRIAGE:1,
        TYPE_MATCH_LOVE:2,
        TYPE_MATCH_ESTROUS:3,
        TYPE_MATCH_PEACH:4,
        TYPE_MATCH_FRIENDSHIP:5,
        TYPE_MATCH_WEALTH:6,
        TYPE_MATCH_LUCK:7
    },
    TYPE_MATCH_INPUT:{
        TYPE_MATCH_UID:0,
        TYPE_MATCH_USER_INFO:1
    }
};